### ISSUE TITLE
What happened with Doodle3D?

### ISSUE THREAD

**Issue by deadln** [Doodle3D/Doodle3D-Core#12]
![image](https://user-images.githubusercontent.com/44840386/222702663-ed7afdd4-8d52-4179-959a-6096b56dacd6.png)
What is this?

**Comment by companje** [comment]
hi @deadln, thanks for your message. We were migrating to a new server today. It should work again now. Can you confirm that?

**Comment by deadln** [comment]
Yes, now I confirm
